stages:
  - style
  - build
  - analyze

format:
  image: alexshcdr/rustc-x86_64-debian11
  stage: style
  script:
    - cargo fmt --check
  tags:
    - docker

x86_64-debian:11:
  image: alexshcdr/rustc-x86_64-debian11
  stage: build
  script:
    - cargo build --release
    - cargo test --release
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_SHA}
    expire_in: 1 days
    paths:
    - target/release/slave*
  tags:
    - docker

x86_64-windows-mingw:
  image: alexshcdr/rustc-x86_64-windows
  stage: build
  script:
    - cargo build --release --target x86_64-pc-windows-gnu
  tags:
    - docker

armv7-debian:11:
  image: alexshcdr/rustc-armv7-debian11
  stage: build
  script:
    - cargo build --release --target=armv7-unknown-linux-gnueabihf
  tags:
    - docker

aarch64-debian:11:
  image: alexshcdr/rustc-aarch64-debian11
  stage: build
  script:
    - cargo build --release --target=aarch64-unknown-linux-gnu
  tags:
    - docker

clippy:
  image: alexshcdr/rustc-x86_64-debian11
  stage: analyze
  needs: [format]
  script:
    - cargo clippy
  tags:
    - docker

miri:
  image: alexshcdr/rustc-x86_64-debian11
  stage: analyze
  needs: [format]
  script:
    - rustup default nightly
    - rustup component add miri
    - rustup update
    - cargo miri test
  tags:
    - docker


